"""PawPal+ — command-line demo.

Builds an owner with two pets and several tasks, then prints today's
schedule generated by the Scheduler. Also demonstrates the sort-by-time
and filtering helpers.
"""

from pawpal_system import Owner, Pet, Scheduler, Task


def build_owner() -> Owner:
    """Create a sample owner with two pets and tasks added OUT OF ORDER."""
    owner = Owner("Gavino", available_minutes=90)

    biscuit = Pet("Biscuit", species="Dog", breed="Golden Retriever", age=3)
    # Deliberately added out of chronological order to test sort_by_time().
    biscuit.add_task(Task("Enrichment puzzle", 20, "low", time="17:00"))
    biscuit.add_task(Task("Morning walk", 30, "high", time="08:00"))
    biscuit.add_task(Task("Feeding", 10, "high", time="09:00"))

    whiskers = Pet("Whiskers", species="Cat", breed="Tabby", age=5)
    whiskers.add_task(Task("Grooming", 25, "medium", time="18:00"))
    # Overlaps Biscuit's Morning walk (08:00–08:30) to trigger a conflict warning.
    whiskers.add_task(Task("Feeding", 10, "high", time="08:15"))

    owner.add_pet(biscuit)
    owner.add_pet(whiskers)
    return owner


def main() -> None:
    owner = build_owner()
    scheduler = Scheduler.for_owner(owner, start_time="08:00")

    # 1) Sorting by time — tasks were added out of order above.
    print("Tasks sorted by time")
    print("=" * 40)
    for task in scheduler.sort_by_time():
        label = task.time or "--:--"
        print(f"  {label} — {task.description} ({task.duration} min)")

    # 2) Filtering by completion status — mark one done, then show open tasks.
    owner.pets[0].get_tasks()[1].mark_complete()  # complete Biscuit's Morning walk
    print("\nOpen (incomplete) tasks")
    print("=" * 40)
    for task in scheduler.filter_by_status(completed=False):
        print(f"  {task.summary()}")

    # 3) Filtering by pet name.
    print("\nWhiskers' tasks only")
    print("=" * 40)
    for task in owner.tasks_for_pet("Whiskers"):
        print(f"  {task.summary()}")

    # 4) Conflict detection — two tasks share an overlapping time slot.
    print("\nConflict check")
    print("=" * 40)
    conflicts = scheduler.detect_conflicts()
    if conflicts:
        for warning in conflicts:
            print(f"  {warning}")

        # Resolve the conflicts by shifting overlapping tasks to a free slot.
        print("\nResolved (conflict-free) timeline")
        print("=" * 40)
        for start, task in scheduler.resolve_conflicts():
            print(f"  {start} — {task.description} ({task.duration} min)")
    else:
        print("  No conflicts detected.")

    # 5) Full generated schedule.
    print("\nToday's Schedule")
    print("=" * 40)
    for start, task in scheduler.generate_plan():
        print(f"  {start} — {task.description} ({task.duration} min)"
              f" [priority: {task.priority}]")


if __name__ == "__main__":
    main()
