"""PawPal+ — command-line demo.

Builds an owner with two pets and several tasks, then prints today's
schedule generated by the Scheduler.
"""

from pawpal_system import Owner, Pet, Scheduler, Task


def build_owner() -> Owner:
    """Create a sample owner with two pets and a handful of tasks."""
    owner = Owner("Gavino", available_minutes=90)

    biscuit = Pet("Biscuit", species="Dog", breed="Golden Retriever", age=3)
    biscuit.add_task(Task("Morning walk", 30, "high", time="08:00"))
    biscuit.add_task(Task("Feeding", 10, "high", time="09:00"))
    biscuit.add_task(Task("Enrichment puzzle", 20, "low", time="17:00"))

    whiskers = Pet("Whiskers", species="Cat", breed="Tabby", age=5)
    whiskers.add_task(Task("Feeding", 10, "high", time="08:30"))
    whiskers.add_task(Task("Grooming", 25, "medium", time="18:00"))

    owner.add_pet(biscuit)
    owner.add_pet(whiskers)
    return owner


def main() -> None:
    owner = build_owner()
    scheduler = Scheduler.for_owner(owner, start_time="08:00")
    plan = scheduler.generate_plan()

    print(f"Today's Schedule for {owner.name}")
    print("=" * 40)
    for start, task in plan:
        print(f"  {start} — {task.description} ({task.duration} min)"
              f" [priority: {task.priority}]")

    print()
    print(scheduler.explain())


if __name__ == "__main__":
    main()
